# Generated by Django 3.2.3 on 2021-07-20 07:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='my',
            options={'ordering': ['id'], 'verbose_name': '* ادمین سایت *', 'verbose_name_plural': '* ادمین سایت *'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-id'], 'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_parented', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='my',
            name='adress_admin',
            field=models.CharField(max_length=1000, null=True, verbose_name='آدرس و موقعیت '),
        ),
        migrations.AddField(
            model_name='my',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_parented', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده سایت'),
        ),
        migrations.AddField(
            model_name='my',
            name='email_admin',
            field=models.EmailField(max_length=100, null=True, verbose_name='ایمیل ادمین '),
        ),
        migrations.AddField(
            model_name='my',
            name='phone_admin',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تماس ادمین '),
        ),
        migrations.AddField(
            model_name='slider',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slider_parented', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='first_app.category', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='my',
            name='copy_site',
            field=models.CharField(max_length=200, null=True, verbose_name='توضیح در مورد جواز کپی از سایت'),
        ),
        migrations.AlterField(
            model_name='my',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات و معرفی درباره سایت'),
        ),
        migrations.AlterField(
            model_name='my',
            name='logo',
            field=models.ImageField(upload_to='my_images', verbose_name='لوگوی سایت'),
        ),
        migrations.AlterField(
            model_name='my',
            name='name_admin',
            field=models.CharField(max_length=100, null=True, verbose_name='نام و نام خانوادگی ادمین'),
        ),
        migrations.AlterField(
            model_name='my',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='مشهوریت سایت با نام'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slid_images', verbose_name='عکس'),
        ),
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_suppurt', models.IntegerField(choices=[(1, 'مالی سایت'), (2, 'آموزش ها'), (3, 'روند ثبت نام و ورود'), (4, 'پیگیری ها'), (5, 'متفرقه'), (6, 'درخواست حذف')], null=True, verbose_name='موضوع پیگیری')),
                ('name_user', models.CharField(max_length=200, null=True, verbose_name='نام و نام خانوادگی کاربر')),
                ('phone_user', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس کاربر ')),
                ('email_user', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل کاربر ')),
                ('description_user', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات برای راهنمایی پشتیبانی سایت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_parented', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پشتیبانی سایت',
                'verbose_name_plural': 'پشتیبانی سایت',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان پست')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='آدرس')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='زمان پست')),
                ('introduction', models.CharField(blank=True, max_length=300, null=True, verbose_name='معرفی کوتاه')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='عکس')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش برای کاربران عمومی')),
                ('preview', models.BooleanField(default=True, verbose_name='پیش نویس')),
                ('audio', models.FileField(blank=True, null=True, upload_to='post_audio', verbose_name='فایل صوتی')),
                ('video', models.FileField(blank=True, null=True, upload_to='post_video', verbose_name='فایل ویدئو')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک یوتیوب یا آپارات')),
                ('title_post', models.IntegerField(choices=[(1, 'مقاله'), (2, 'پادکست'), (3, 'ویدئو')], null=True, verbose_name='عنوان پست')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parented', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parented', to='first_app.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-id'],
            },
        ),
    ]
