# Generated by Django 3.2.3 on 2021-07-20 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0002_auto_20210720_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_parented', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
