# Generated by Django 3.2.3 on 2021-07-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210720_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
