# Generated by Django 3.2.3 on 2021-05-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='post', null=True, unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True, verbose_name='نمایش برای کاربران عمومی'),
        ),
    ]
