# Generated by Django 3.2.3 on 2021-07-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_post_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_post',
            field=models.IntegerField(choices=[(1, 'مقاله'), (2, 'پادکست'), (3, 'ویدئو')], null=True, verbose_name='عنوان پست'),
        ),
    ]
