# Generated by Django 3.2.3 on 2021-07-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20210718_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک یوتیوب یا آپارات'),
        ),
    ]
