# Generated by Django 3.2.3 on 2021-07-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_alter_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='معرفی کوتاه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parented', to='first_app.category', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.IntegerField(blank=True, choices=[(1, 'مقاله'), (2, 'پادکست'), (3, 'ویدئو')], null=True, verbose_name='عنوان پست'),
        ),
    ]
