# Generated by Django 3.2.3 on 2021-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.CharField(max_length=300, null=True, verbose_name='معرفی کوتاه'),
        ),
    ]
