# Generated by Django 3.2.3 on 2021-05-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='my',
            name='logo',
            field=models.ImageField(upload_to='my_images', verbose_name='لوگوی من'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slid_images', verbose_name='عکس'),
        ),
    ]
