# Generated by Django 3.2.3 on 2021-06-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20210531_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
