# Generated by Django 3.2.3 on 2021-07-06 20:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20210630_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='my',
            name='adress_admin',
            field=models.CharField(max_length=1000, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='my',
            name='email_admin',
            field=models.EmailField(max_length=100, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='my',
            name='phone_admin',
            field=models.IntegerField(max_length=12, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='my',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='درباره من'),
        ),
    ]
