# Generated by Django 3.2.3 on 2021-07-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_auto_20210707_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my',
            name='phone_admin',
            field=models.CharField(max_length=12, null=True, verbose_name='شماره تماس'),
        ),
    ]
