# Generated by Django 3.2.3 on 2021-07-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_alter_my_phone_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my',
            name='phone_admin',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تماس'),
        ),
    ]
