# Generated by Django 3.2.3 on 2021-07-07 22:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_auto_20210708_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_suppurt', models.CharField(max_length=200, null=True, verbose_name='موضوع پیگیری')),
                ('name_user', models.CharField(max_length=200, null=True, verbose_name='نام و نام خانوادگی ادمین')),
                ('phone_user', models.CharField(max_length=11, null=True, verbose_name='شماره تماس ادمین ')),
                ('email_user', models.EmailField(max_length=100, null=True, verbose_name='ایمیل ادمین ')),
                ('description_user', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='نوضیحات برای راهنمایی پشتیبانی سایت')),
            ],
            options={
                'verbose_name': 'پشتیبانی سایت',
                'verbose_name_plural': 'پشتیبانی سایت',
            },
        ),
        migrations.AlterField(
            model_name='my',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات و معرفی درباره سایت'),
        ),
    ]
