# Generated by Django 3.2.3 on 2021-07-08 11:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0019_auto_20210708_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_parented', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='support',
            name='description_user',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات برای راهنمایی پشتیبانی سایت'),
        ),
        migrations.AlterField(
            model_name='support',
            name='email_user',
            field=models.EmailField(max_length=100, null=True, verbose_name='ایمیل کاربر '),
        ),
        migrations.AlterField(
            model_name='support',
            name='name_user',
            field=models.CharField(max_length=200, null=True, verbose_name='نام و نام خانوادگی کاربر'),
        ),
        migrations.AlterField(
            model_name='support',
            name='phone_user',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تماس کاربر '),
        ),
    ]
