# Generated by Django 3.2.3 on 2021-07-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_auto_20210708_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='name_user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی کاربر'),
        ),
    ]
