# Generated by Django 3.2.3 on 2021-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_alter_support_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='name_user',
            field=models.CharField(max_length=200, null=True, verbose_name='نام و نام خانوادگی کاربر'),
        ),
    ]
