# Generated by Django 3.2.3 on 2021-07-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0022_alter_support_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.BooleanField(default=True, verbose_name='پیش نویس یا منتشر شده؟'),
        ),
    ]
