# Generated by Django 3.2.3 on 2021-07-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_post_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.BooleanField(default=True, verbose_name='پیش نویس'),
        ),
    ]
