# Generated by Django 3.2.3 on 2021-07-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0025_auto_20210711_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiadress',
            options={'verbose_name': 'آی پی آدرس', 'verbose_name_plural': 'آی پی آدرس ها'},
        ),
    ]
