# Generated by Django 3.2.3 on 2021-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0028_alter_support_title_suppurt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='title_suppurt',
            field=models.IntegerField(choices=[('مالی سایت', 'مالی سایت'), ('آموزش ها', 'آموزش ها'), ('روند ثبت نام و ورود', 'روند ثبت نام و ورود'), ('پیگیری ها', 'پیگیری ها'), ('متفرقه', 'متفرقه')], null=True, verbose_name='موضوع پیگیری'),
        ),
    ]
