# Generated by Django 3.2.3 on 2021-07-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0030_alter_support_title_suppurt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.DeleteModel(
            name='Apiadress',
        ),
    ]
