# Generated by Django 3.2.3 on 2021-07-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0030_alter_support_title_suppurt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='my',
            options={'ordering': ['id'], 'verbose_name': '* ادمین سایت *', 'verbose_name_plural': '* ادمین سایت *'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-id'], 'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر'},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-id'], 'verbose_name': 'پشتیبانی سایت', 'verbose_name_plural': 'پشتیبانی سایت'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.AlterField(
            model_name='support',
            name='title_suppurt',
            field=models.IntegerField(choices=[(1, 'مالی سایت'), (2, 'آموزش ها'), (3, 'روند ثبت نام و ورود'), (4, 'پیگیری ها'), (5, 'متفرقه'), (6, 'درخواست حذف')], null=True, verbose_name='موضوع پیگیری'),
        ),
        migrations.DeleteModel(
            name='Apiadress',
        ),
    ]
