# Generated by Django 3.2.3 on 2021-07-12 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0031_auto_20210712_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان تاسیس'),
        ),
        migrations.AlterField(
            model_name='support',
            name='title_suppurt',
            field=models.IntegerField(choices=[(1, 'مالی سایت'), (2, 'آموزش ها'), (3, 'روند ثبت نام و ورود'), (4, 'پیگیری ها'), (5, 'متفرقه'), (6, 'درخواست حذف')], null=True, verbose_name='موضوع پیگیری'),
        ),
    ]
