# Generated by Django 3.2.3 on 2021-07-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0032_auto_20210712_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
    ]
