# Generated by Django 3.2.3 on 2021-07-12 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0033_auto_20210712_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-date'], 'verbose_name': 'پشتیبانی سایت', 'verbose_name_plural': 'پشتیبانی سایت'},
        ),
        migrations.AddField(
            model_name='support',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان درخواست'),
        ),
    ]
