# Generated by Django 3.2.3 on 2021-07-12 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0034_auto_20210712_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان درخواست'),
        ),
    ]
